# ingress/preview/ingress-preview.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress-preview
  labels:
    app.kubernetes.io/name: petclinic-ingress-preview
spec:
  rules:
    - host: "{{featureName}}.petclinic.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
