# values/preview/test-vet-1/values.yaml
image:
  repository: hzeroxium/spring-petclinic-vets-service
  tag: "45d9ee0"
  pullPolicy: IfNotPresent

replicas: 1

ingress:
  enabled: true
  name: test-vet-1-ingress
  host: test-vet-1.petclinic.local

service:
  port: 8083
  type: ClusterIP

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: CONFIG_SERVER_URL
    value: http://config-server.petclinic-dev.svc.cluster.local:8888
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: http://discovery-server.petclinic-dev.svc.cluster.local:8761/eureka
